# Site settings
title: Talon
email: talon@theghostin.me
description: "Talon lives."
baseurl: ""
url: "theghostin.me"
twitter_username: legittalon
github_username: legittalon

# Build settings
markdown: kramdown
permalink: pretty

# highlighter: pygments

sass:
  sass_dir: _sass

# Defaults
defaults:
  -
    scope:
      path: "" # all
      type: "posts"
    values:
      layout: "posts"
